global:
  resolve_timeout: 5m
  smtp_smarthost: {{ index .Params "SMTPHost" }}:{{ index .Params "SMTPPort" }}
  smtp_from: noreply@{{ index .Params "AlertManagerRoute" }}
  smtp_auth_username: {{ index .Params "SMTPUsername" }}
  smtp_auth_password: {{ index .Params "SMTPPassword"}}
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
  routes:
    - match:
        severity: critical
      receiver: critical
    - match:
        alertname: DeadMansSwitch
      repeat_interval: 5m
      receiver: deadmansswitch
receivers:
  - name: default
    email_configs:
      - send_resolved: true
        to: {{ index .Params "SMTPToAddress" }}
  - name: critical
    pagerduty_configs:
      - service_key: {{ index .Params "PagerDutyServiceKey" }}
    email_configs:
      - send_resolved: true
        to: {{ index .Params "SMTPToAddress" }}
  - name: deadmansswitch
    webhook_configs:
      - url: {{ index .Params "DeadMansSnitchURL" }}
inhibit_rules:
  - source_match:
      alertname: 'JobRunningTimeExceeded'
      severity: 'critical'
    target_match:
      alertname: 'JobRunningTimeExceeded'
      severity: 'warning'
    equal: ['alertname', 'job', 'label_cronjob_name']